package com.tdc.sheets.entity.enums;

/**
 * Enum para tipos de equipamentos conforme definido no sistema TDC
 */
public enum TiposEquipamentos {
    PEDRAS_PRECIOSAS,
    OBRAS_ARTES,
    MERCADORIAS_TECIDOS,
    MERCADORIAS_METAIS,
    MERCADORIAS_ANIMAIS,
    MERCADORIAS_PROVISOES,
    AVENTURA_EXPLORACAO_VIAGEM,
    COMIDA_BEBIDA,
    FEITICARIA_CONDUITES,
    FEITICARIA_POCOES,
    FEITICARIA_OUTROS,
    FERRAMENTAS_HABILIDADE,
    FERRAMENTAS_OFICIO,
    FONTES_LUZ,
    HERBALISMO,
    INSTRUMENTOS_MUSICAIS,
    MUNICOES,
    PRODUTOS_ALQUIMICOS,
    RECIPIENTES,
    UTILITARIOS,
    VENENOS,
    VESTIMENTAS,
    ARMAS_SIMPLES,
    ARMAS_MARCIAIS,
    ARMAS_COMPLEXAS,
    ARMAS_PESADAS,
    PROTECOES_LEVES,
    PROTECOES_MEDIAS,
    PROTECOES_PESADAS,
    ESCUDOS,
    TRALHA,
    MATERIAIS_INGREDIENTES,
    MATERIAIS_CRIACAO
}
